{
  "props": [],
  "components": {
    "clear": {
      "type": "script\\MacroScript",
      "x": 304,
      "y": 192,
      "props": {}
    },
    "getInfo": {
      "type": "script\\MacroScript",
      "x": 96,
      "y": 192,
      "props": {}
    },
    "openBuild": {
      "type": "script\\MacroScript",
      "x": 304,
      "y": 112,
      "props": {}
    },
    "chooserFileOpen": {
      "type": "script\\FileChooserScript",
      "x": 96,
      "y": 112,
      "props": {
        "filterName": "Все файлы",
        "filterExtensions": "*",
        "filterAny": "0",
        "inputNode": ""
      }
    },
    "chooserFileSave": {
      "type": "script\\FileChooserScript",
      "x": 96,
      "y": 32,
      "props": {
        "saveDialog": true,
        "filterName": "Все файлы",
        "filterExtensions": "*",
        "filterAny": "0",
        "inputNode": ""
      }
    },
    "loadContent": {
      "type": "script\\MacroScript",
      "x": 304,
      "y": 32,
      "props": {}
    }
  }
}